author: Tobe O <thosakwe@gmail.com>
description: Generates recursive descent parsers in Dart from EBNF grammars.
homepage: https://github.com/thosakwe/backus.git
name: backus
version: 0.0.0
dependencies:
  build: ^0.9.0
  code_builder: ^1.0.0
  compiler_tools: ^1.0.0-dev
  inflection: ^0.4.1
  recase: ^1.0.0
dev_dependencies:
  build_runner: ^0.3.0
  test: ^0.12.0
environment: 
  sdk: ">=1.19.0"
